apiVersion: v1
kind: Service
metadata:
  name: insurance-service
  namespace: thread-pilot-$DEPLOYMENT_ENV
spec:
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: insurance-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-service
  namespace: thread-pilot-$DEPLOYMENT_ENV
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-service
  template:
    metadata:
      labels:
        app: insurance-service
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: $DEPLOYMENT_ENV
        image: $DOCKER_IMAGE
        imagePullPolicy: Always
        name: insurance-service-container
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: insurance-service
  namespace: thread-pilot-$DEPLOYMENT_ENV
spec:
  rules:
    - host: insurance.$DEPLOYMENT_ENV.thread-pilot.int.mindphaser.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: insurance-service
                port:
                  number: 8082
