apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
  namespace: thread-pilot-$DEPLOYMENT_ENV
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: vehicle-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-service
  namespace: thread-pilot-$DEPLOYMENT_ENV
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-service
  template:
    metadata:
      labels:
        app: vehicle-service
    spec:
      containers:
      - env:
        - name: DUMMY
          value: value
        image: $DOCKER_IMAGE
        imagePullPolicy: Always
        name: vehicle-service-container
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: vehicle-service
  namespace: thread-pilot-$DEPLOYMENT_ENV
spec:
  rules:
    - host: vehicle.$DEPLOYMENT_ENV.thread-pilot.int.mindphaser.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vehicle-service
                port:
                  number: 8081
